baseURL = "http://lambdada.org/"
languageCode = "fr"
title = "lambdada.org"
theme = "hugo-xmin"
publishDir = "docs"

[[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Sessions"
    url = "/session/"
    weight = 3    
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
